"""add insights table

Revision ID: 554436b298f2
Revises: f379fd4fc535
Create Date: 2026-05-22 12:40:21.614803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554436b298f2'
down_revision: Union[str, Sequence[str], None] = 'f379fd4fc535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('week_end', sa.Date(), nullable=True),
    sa.Column('content_md', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(length=32), nullable=True),
    sa.Column('llm_model', sa.String(length=64), nullable=True),
    sa.Column('input_context_hash', sa.String(length=64), nullable=True),
    sa.Column('context_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_input_context_hash'), ['input_context_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_target_date'), ['target_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insights_type'))
        batch_op.drop_index(batch_op.f('ix_insights_target_date'))
        batch_op.drop_index(batch_op.f('ix_insights_input_context_hash'))
        batch_op.drop_index(batch_op.f('ix_insights_generated_at'))

    op.drop_table('insights')
    # ### end Alembic commands ###
