"""add garmin tables

Revision ID: a935e6c74866
Revises: f3e2a43c9798
Create Date: 2026-05-21 21:26:32.110095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a935e6c74866'
down_revision: Union[str, Sequence[str], None] = 'f3e2a43c9798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('lean_mass_kg', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_metrics_date'), ['date'], unique=False)

    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_min', sa.Integer(), nullable=True),
    sa.Column('body_battery_start', sa.Integer(), nullable=True),
    sa.Column('body_battery_end', sa.Integer(), nullable=True),
    sa.Column('stress_avg', sa.Integer(), nullable=True),
    sa.Column('hrv_avg', sa.Float(), nullable=True),
    sa.Column('training_readiness', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('valid_as_of_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('garmin_activities',
    sa.Column('activity_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sport_type', sa.String(length=64), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('hr_avg', sa.Integer(), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True),
    sa.Column('training_effect_aerobic', sa.Float(), nullable=True),
    sa.Column('training_effect_anaerobic', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    with op.batch_alter_table('garmin_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garmin_activities_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garmin_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garmin_activities_date'))

    op.drop_table('garmin_activities')
    op.drop_table('daily_metrics')
    with op.batch_alter_table('body_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_metrics_date'))

    op.drop_table('body_metrics')
    # ### end Alembic commands ###
