"""add sessions tables

Revision ID: f379fd4fc535
Revises: a935e6c74866
Create Date: 2026-05-21 21:40:50.285921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f379fd4fc535'
down_revision: Union[str, Sequence[str], None] = 'a935e6c74866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_slug', sa.String(length=128), nullable=False),
    sa.Column('workout_template_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('garmin_activity_id', sa.Integer(), nullable=True),
    sa.Column('activity_link_source', sa.String(length=16), nullable=True),
    sa.Column('note', sa.String(length=4096), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garmin_activity_id'], ['garmin_activities.activity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_garmin_activity_id'), ['garmin_activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_plan_slug'), ['plan_slug'], unique=False)

    op.create_table('session_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('block_idx', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=128), nullable=False),
    sa.Column('set_idx', sa.Integer(), nullable=False),
    sa.Column('planned_reps', sa.Integer(), nullable=True),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight_kg', sa.Float(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('is_dropset_continuation', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_sets_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_sets_session_id'), ['session_id'], unique=False)

    op.create_table('tested_1rm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps_done', sa.Integer(), nullable=False),
    sa.Column('estimated_1rm', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tested_1rm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tested_1rm_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tested_1rm_exercise_id'), ['exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tested_1rm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tested_1rm_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_tested_1rm_date'))

    op.drop_table('tested_1rm')
    with op.batch_alter_table('session_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_sets_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_sets_exercise_id'))

    op.drop_table('session_sets')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_plan_slug'))
        batch_op.drop_index(batch_op.f('ix_sessions_garmin_activity_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_date'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
