/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        /** Put Profile */
        put: operations["put_profile_api_profile_put"];
        post?: never;
        /**
         * Delete Profile
         * @description Delete profile.yaml. Used by onboarding wizard reset.
         */
        delete: operations["delete_profile_api_profile_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile Exists */
        get: operations["profile_exists_api_profile_exists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_exercises_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_api_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plans__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{slug}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_api_plans__slug__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{slug}/schedule/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Schedule
         * @description Re-run the scheduling agent against the user's current profile.
         */
        post: operations["regenerate_schedule_api_plans__slug__schedule_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage */
        get: operations["usage_api_llm_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/garmin/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_api_garmin_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/garmin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_garmin_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/garmin/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily */
        get: operations["daily_api_garmin_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/garmin/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activities */
        get: operations["activities_api_garmin_activities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workout Today */
        get: operations["workout_today_api_workouts_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Post Session */
        post: operations["post_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Activity */
        patch: operations["patch_activity_api_sessions__session_id__activity_patch"];
        trace?: never;
    };
    "/api/sessions/exercises/{exercise_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exercise History */
        get: operations["exercise_history_api_sessions_exercises__exercise_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_briefing_today_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Briefings */
        get: operations["list_briefings_api_briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefing/{briefing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Briefing */
        get: operations["get_briefing_api_briefing__briefing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_reports_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_reports__report_id__get"];
        put?: never;
        post?: never;
        /** Delete Report */
        delete: operations["delete_report_api_reports__report_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityRow */
        ActivityRow: {
            /** Activity Id */
            activity_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sport Type */
            sport_type: string | null;
            /** Duration S */
            duration_s: number | null;
            /** Distance Km */
            distance_km: number | null;
            /** Hr Avg */
            hr_avg: number | null;
            /** Hr Max */
            hr_max: number | null;
            /** Training Effect Aerobic */
            training_effect_aerobic: number | null;
            /** Training Effect Anaerobic */
            training_effect_anaerobic: number | null;
        };
        /** AuthStatus */
        AuthStatus: {
            /** Authenticated */
            authenticated: boolean;
            /** Auth Required */
            auth_required: boolean;
        };
        /**
         * BiSetBlock
         * @description Two (or more) exercises alternated without rest between them.
         */
        BiSetBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "biset";
            /** Rounds */
            rounds: number;
            /** Exercises */
            exercises: components["schemas"]["BiSetExercise"][];
            rest: components["schemas"]["RestSpec"];
            /** Video Urls */
            video_urls?: string[];
        };
        /** BiSetExercise */
        BiSetExercise: {
            exercise: components["schemas"]["ExerciseRef"];
            /** Reps */
            reps: number;
        };
        /** BodyBatteryPoint */
        BodyBatteryPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Level */
            level: number;
        };
        /** BriefingListItem */
        BriefingListItem: {
            /** Id */
            id: number;
            /** Target Date */
            target_date: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Llm Provider */
            llm_provider: string | null;
            /** Llm Model */
            llm_model: string | null;
        };
        /** BriefingResponse */
        BriefingResponse: {
            /** Id */
            id: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Content Md */
            content_md: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Llm Provider */
            llm_provider: string | null;
            /** Llm Model */
            llm_model: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /** ContinuousRunBlock */
        ContinuousRunBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "continuous_run";
            /** Name */
            name?: string | null;
            /** Segments */
            segments: components["schemas"]["RunSegment"][];
            /** Video Url */
            video_url?: string | null;
        };
        /** DailyMetricRow */
        DailyMetricRow: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sleep Score */
            sleep_score: number | null;
            /** Sleep Duration Min */
            sleep_duration_min: number | null;
            /** Body Battery Start */
            body_battery_start: number | null;
            /** Body Battery End */
            body_battery_end: number | null;
            /** Stress Avg */
            stress_avg: number | null;
            /** Hrv Avg */
            hrv_avg: number | null;
            /** Training Readiness */
            training_readiness: number | null;
            /** Weight Kg */
            weight_kg: number | null;
        };
        /** DailyTrendRow */
        DailyTrendRow: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sleep Score */
            sleep_score: number | null;
            /** Sleep Duration Min */
            sleep_duration_min: number | null;
            /** Hrv Avg */
            hrv_avg: number | null;
            /** Body Battery Start */
            body_battery_start: number | null;
            /** Body Battery End */
            body_battery_end: number | null;
            /** Stress Avg */
            stress_avg: number | null;
        };
        /** DashboardResponse */
        DashboardResponse: {
            today: components["schemas"]["TodayCard"];
            /** Trend */
            trend: components["schemas"]["DailyTrendRow"][];
            /** Body Battery Intraday */
            body_battery_intraday: components["schemas"]["BodyBatteryPoint"][];
            /** Weekly Volume */
            weekly_volume: components["schemas"]["WeeklyVolumeRow"][];
            /** Recent Activities */
            recent_activities: components["schemas"]["RecentActivity"][];
            vo2_max?: components["schemas"]["VO2MaxCard"] | null;
        };
        /**
         * DropsetBlock
         * @description Initial set to failure; reduce weight; continue.
         */
        DropsetBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "dropset";
            exercise: components["schemas"]["ExerciseRef"];
            /** Sets */
            sets: number;
            rest: components["schemas"]["RestSpec"];
            /** Description */
            description?: string | null;
            /** Video Url */
            video_url?: string | null;
        };
        /** Exercise */
        Exercise: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[];
            /**
             * Primary Muscle Group
             * @enum {string}
             */
            primary_muscle_group: "quads" | "hamstrings" | "glutes" | "calves" | "adductors" | "abductors" | "chest" | "back" | "shoulders" | "biceps" | "triceps" | "forearms" | "abs" | "core" | "lower_back" | "full_body";
            /** Secondary Muscle Groups */
            secondary_muscle_groups?: ("quads" | "hamstrings" | "glutes" | "calves" | "adductors" | "abductors" | "chest" | "back" | "shoulders" | "biceps" | "triceps" | "forearms" | "abs" | "core" | "lower_back" | "full_body")[];
            /**
             * Equipment
             * @enum {string}
             */
            equipment: "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "kettlebell" | "smith" | "band" | "other";
            /** Video Url */
            video_url?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ExerciseRef
         * @description Reference to an exercise. `exercise_id` is set after catalog matching.
         *
         *     `raw_name` is preserved from the PDF, so we can re-match if the catalog
         *     grows. `confidence` is filled by the matcher (0..1).
         */
        ExerciseRef: {
            /** Exercise Id */
            exercise_id?: string | null;
            /** Raw Name */
            raw_name: string;
            /** Confidence */
            confidence?: number | null;
        };
        /** FartlekBlock */
        FartlekBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "fartlek";
            /** Name */
            name?: string | null;
            /** Segments */
            segments: components["schemas"]["RunSegment"][];
            /** Video Url */
            video_url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Db Ok */
            db_ok: boolean;
        };
        /** IntervalRunBlock */
        IntervalRunBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "interval_run";
            /** Name */
            name?: string | null;
            /** Segments */
            segments: components["schemas"]["RunSegment"][];
            /** Video Url */
            video_url?: string | null;
        };
        /** LinkRequest */
        LinkRequest: {
            /** Activity Id */
            activity_id: number | null;
        };
        /** LinkedActivity */
        LinkedActivity: {
            /** Activity Id */
            activity_id: number;
            /** Sport Type */
            sport_type: string | null;
            /** Duration S */
            duration_s: number | null;
            /** Distance Km */
            distance_km: number | null;
            /** Hr Avg */
            hr_avg: number | null;
            /** Hr Max */
            hr_max: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /**
         * MetaRepsBlock
         * @description N sets × fixed reps, load is user-chosen at execution time.
         */
        MetaRepsBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "meta_reps";
            exercise: components["schemas"]["ExerciseRef"];
            /** Sets */
            sets: number;
            /** Reps */
            reps: number;
            rest: components["schemas"]["RestSpec"];
            /** Video Url */
            video_url?: string | null;
        };
        /** OneRMRow */
        OneRMRow: {
            /** Exercise Id */
            exercise_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg: number;
            /** Reps Done */
            reps_done: number;
            /** Estimated 1Rm */
            estimated_1rm: number;
            /** Source */
            source: string;
        };
        /** Plan */
        Plan: {
            /** Name */
            name: string;
            /** Level */
            level?: string | null;
            /** Goal */
            goal?: string | null;
            /** Weeks Duration */
            weeks_duration?: number | null;
            /** Templates */
            templates: {
                [key: string]: components["schemas"]["WorkoutTemplate"];
            };
            /** Schedule */
            schedule?: {
                [key: string]: string[];
            };
            /** Schedule Rationale */
            schedule_rationale?: string | null;
            /** Source Pdf */
            source_pdf?: string | null;
        };
        /** PlannedExercise */
        PlannedExercise: {
            /** Block Idx */
            block_idx: number;
            /** Exercise Id */
            exercise_id: string;
            /** Exercise Name */
            exercise_name: string;
            /** Sets */
            sets: components["schemas"]["PlannedSet"][];
            /** Rest Seconds */
            rest_seconds?: number | null;
            /** Kind */
            kind: string;
            /** Notes */
            notes?: string | null;
        };
        /** PlannedSet */
        PlannedSet: {
            /** Set Idx */
            set_idx: number;
            /** Planned Reps */
            planned_reps?: number | null;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
        };
        /** PlannedWorkout */
        PlannedWorkout: {
            /** Plan Slug */
            plan_slug: string;
            /** Template Id */
            template_id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Exercises */
            exercises: components["schemas"]["PlannedExercise"][];
        };
        /**
         * Profile
         * @description Static profile, lives in data/profile.yaml committed to the repo.
         *
         *     Dynamic data (weight, body comp over time) goes into the SQLite
         *     `body_metrics` table instead.
         */
        Profile: {
            /** Name */
            name: string;
            /**
             * Birthdate
             * Format: date
             */
            birthdate: string;
            /**
             * Sex
             * @enum {string}
             */
            sex: "M" | "F";
            /** Height Cm */
            height_cm: number;
            /** Fc Max Bpm */
            fc_max_bpm: number;
            /**
             * Fc Max Source
             * @default tanaka
             * @enum {string}
             */
            fc_max_source: "tanaka" | "garmin" | "tested";
            /** Training Days */
            training_days?: ("mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun")[];
            /** Notes */
            notes?: string | null;
        };
        /**
         * PyramidBlock
         * @description N sets with decreasing reps (e.g., 15-12-10-8); load usually progresses.
         */
        PyramidBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pyramid";
            exercise: components["schemas"]["ExerciseRef"];
            /** Reps Per Set */
            reps_per_set: number[];
            rest: components["schemas"]["RestSpec"];
            /** Video Url */
            video_url?: string | null;
        };
        /** RecentActivity */
        RecentActivity: {
            /** Activity Id */
            activity_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sport Type */
            sport_type: string | null;
            /** Duration Min */
            duration_min: number | null;
            /** Distance Km */
            distance_km: number | null;
            /** Hr Avg */
            hr_avg: number | null;
        };
        /** ReportListItem */
        ReportListItem: {
            /** Id */
            id: number;
            /** Week Start */
            week_start: string | null;
            /** Week End */
            week_end: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Llm Model */
            llm_model: string | null;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Id */
            id: number;
            /** Week Start */
            week_start: string | null;
            /** Week End */
            week_end: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Content Md */
            content_md: string;
            /** Llm Provider */
            llm_provider: string | null;
            /** Llm Model */
            llm_model: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * RestSpec
         * @description Rest interval between sets.
         */
        RestSpec: {
            /** Seconds */
            seconds?: number | null;
            /** Min Seconds */
            min_seconds?: number | null;
            /** Max Seconds */
            max_seconds?: number | null;
            /** Note */
            note?: string | null;
        };
        /**
         * RunSegment
         * @description One segment: e.g., 6 reps × 500m @ Z5, or 6km @ Z3, or 5min @ Z1.
         */
        RunSegment: {
            /**
             * Repeats
             * @default 1
             */
            repeats: number;
            /** Distance Km */
            distance_km?: number | null;
            /** Duration Min */
            duration_min?: number | null;
            /**
             * Hr Zone
             * @enum {string}
             */
            hr_zone: "Z1" | "Z2" | "Z3" | "Z4" | "Z5";
            /** Note */
            note?: string | null;
        };
        /** SessionCreate */
        SessionCreate: {
            /** Plan Slug */
            plan_slug: string;
            /** Workout Template Id */
            workout_template_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Status
             * @default done
             */
            status: string;
            /** Note */
            note?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Sets */
            sets: components["schemas"]["SetInput"][];
        };
        /** SessionCreateResponse */
        SessionCreateResponse: {
            /** Id */
            id: number;
            /** Auto Linked Activity Id */
            auto_linked_activity_id: number | null;
            /** Derived 1Rm */
            derived_1rm: {
                [key: string]: unknown;
            }[];
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /** Plan Slug */
            plan_slug: string;
            /** Workout Template Id */
            workout_template_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Status */
            status: string;
            /** Note */
            note: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Garmin Activity Id */
            garmin_activity_id: number | null;
            /** Activity Link Source */
            activity_link_source: string | null;
            activity?: components["schemas"]["LinkedActivity"] | null;
            /** Sets */
            sets: components["schemas"]["SetOut"][];
        };
        /** SetInput */
        SetInput: {
            /** Block Idx */
            block_idx: number;
            /** Exercise Id */
            exercise_id: string;
            /** Set Idx */
            set_idx: number;
            /** Planned Reps */
            planned_reps?: number | null;
            /** Actual Reps */
            actual_reps?: number | null;
            /** Actual Weight Kg */
            actual_weight_kg?: number | null;
            /**
             * Is Warmup
             * @default false
             */
            is_warmup: boolean;
            /**
             * Is Dropset Continuation
             * @default false
             */
            is_dropset_continuation: boolean;
            /** Note */
            note?: string | null;
        };
        /** SetOut */
        SetOut: {
            /** Block Idx */
            block_idx: number;
            /** Exercise Id */
            exercise_id: string;
            /** Set Idx */
            set_idx: number;
            /** Planned Reps */
            planned_reps: number | null;
            /** Actual Reps */
            actual_reps: number | null;
            /** Actual Weight Kg */
            actual_weight_kg: number | null;
            /** Is Warmup */
            is_warmup: boolean;
            /** Is Dropset Continuation */
            is_dropset_continuation: boolean;
            /** Note */
            note: string | null;
        };
        /** SyncResponse */
        SyncResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Activities */
            activities: number;
            /** Daily */
            daily: boolean;
            /** Body */
            body: boolean;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
        };
        /** SyncRunRow */
        SyncRunRow: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /**
             * Ran At
             * Format: date-time
             */
            ran_at: string;
            /** Status */
            status: string;
            /** Items Pulled */
            items_pulled: number;
            /** Error */
            error: string | null;
        };
        /** TabataBlock */
        TabataBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "tabata";
            /** Rounds */
            rounds: number;
            /** Description */
            description: string;
            /**
             * Work S
             * @default 20
             */
            work_s: number;
            /**
             * Rest S
             * @default 10
             */
            rest_s: number;
            /**
             * Rounds Per Set
             * @default 8
             */
            rounds_per_set: number;
            rest?: components["schemas"]["RestSpec"] | null;
            /** Video Url */
            video_url?: string | null;
        };
        /** TaskUsage */
        TaskUsage: {
            /** Task Id */
            task_id: string;
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd Estimate */
            cost_usd_estimate: number | null;
        };
        /** TodayCard */
        TodayCard: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sleep Score */
            sleep_score: number | null;
            /** Sleep Duration Min */
            sleep_duration_min: number | null;
            /** Sleep Score 7D Avg */
            sleep_score_7d_avg: number | null;
            /** Body Battery Start */
            body_battery_start: number | null;
            /** Body Battery End */
            body_battery_end: number | null;
            /** Body Battery Now */
            body_battery_now: number | null;
            /** Stress Avg */
            stress_avg: number | null;
            /** Stress 7D Avg */
            stress_7d_avg: number | null;
            /** Hrv Avg */
            hrv_avg: number | null;
            /** Hrv 7D Avg */
            hrv_7d_avg: number | null;
            /** Valid As Of */
            valid_as_of: string | null;
        };
        /** UsageSummary */
        UsageSummary: {
            /** Range Days */
            range_days: number;
            /** Total Calls */
            total_calls: number;
            /** Total Input Tokens */
            total_input_tokens: number;
            /** Total Output Tokens */
            total_output_tokens: number;
            /** Total Cost Usd Estimate */
            total_cost_usd_estimate: number;
            /** By Task */
            by_task: components["schemas"]["TaskUsage"][];
        };
        /** VO2MaxCard */
        VO2MaxCard: {
            /** Value */
            value: number;
            /**
             * Measured At
             * Format: date
             */
            measured_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarmupSuggestion
         * @description Pre-workout suggestion. Not logged; surfaced in briefing as 'preparação'.
         */
        WarmupSuggestion: {
            /** Description */
            description: string;
            /** Duration Min */
            duration_min?: number | null;
            /** Video Url */
            video_url?: string | null;
        };
        /** WeeklyVolumeRow */
        WeeklyVolumeRow: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Week Label */
            week_label: string;
            /** Strength Sessions */
            strength_sessions: number;
            /** Run Count */
            run_count: number;
            /** Run Km */
            run_km: number;
            /** Run Minutes */
            run_minutes: number;
        };
        /** WorkoutTemplate */
        WorkoutTemplate: {
            /** Template Id */
            template_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "strength" | "run";
            /** Warmups */
            warmups?: components["schemas"]["WarmupSuggestion"][];
            /** Blocks */
            blocks: (components["schemas"]["MetaRepsBlock"] | components["schemas"]["PyramidBlock"] | components["schemas"]["BiSetBlock"] | components["schemas"]["DropsetBlock"] | components["schemas"]["TabataBlock"] | components["schemas"]["IntervalRunBlock"] | components["schemas"]["ContinuousRunBlock"] | components["schemas"]["FartlekBlock"])[];
            /** Notes */
            notes?: string | null;
        };
        /** WorkoutTodayResponse */
        WorkoutTodayResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Plan Slug */
            plan_slug: string | null;
            /** Is Rest Day */
            is_rest_day: boolean;
            /** Workouts */
            workouts: components["schemas"]["PlannedWorkout"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"] | null;
                };
            };
        };
    };
    put_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_profile_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    profile_exists_api_profile_exists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_exercises_api_exercises_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
        };
    };
    get_exercise_api_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_plan_api_plans__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_plans__slug__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_schedule_api_plans__slug__schedule_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_api_llm_usage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_api_garmin_sync_post: {
        parameters: {
            query?: {
                /** @description defaults to yesterday */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_garmin_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_api_garmin_daily_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyMetricRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activities_api_garmin_activities_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workout_today_api_workouts_today_get: {
        parameters: {
            query?: {
                /** @description defaults to today */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutTodayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_activity_api_sessions__session_id__activity_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exercise_history_api_sessions_exercises__exercise_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
                since_days?: number;
            };
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OneRMRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_briefing_today_post: {
        parameters: {
            query?: {
                /** @description defaults to today */
                date?: string | null;
                refresh_garmin?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_briefings_api_briefing_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_briefing_api_briefing__briefing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                briefing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_reports_generate_post: {
        parameters: {
            query?: {
                week_start?: string | null;
                week_end?: string | null;
                send_email?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_reports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_report_api_reports__report_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
}
